name: Kiul-Duels-V2
version: '${project.version}'
main: kiul.kiulduelsv2.Kiulduelsv2
api-version: 1.20
commands:
  arena:
    description: arenas
  kit:
    description: kits
  testgeneration:
    description: tests generation
  reroll:
    description: for re-rolling the map in the pregame phase of a realistic duel.
  test:
    description: tests what im testing
  t:
  e:
  cancel:
  save:
  party:
  recap:
  duel:
  previewinv:
  spectate:
permissions:
  kiulduels.extraslots:
    description: gives you access to extra kit slots
    default: false